theme: jekyll-theme-minimal
title: Richard Barella
description: Software Engineer at Intel
logo: https://media-exp1.licdn.com/dms/image/C5603AQEjpWRtfGTu9Q/profile-displayphoto-shrink_200_200/0/1593112650172?e=1673481600&v=beta&t=iuG8juEG6Po8z9gK1oNfwZManqLK-nZn2oYVV8mwwj4
show_downloads: false
