theme: jekyll-theme-minimal
title: Richard Barella
description: Software Engineer at Intel
logo: https://media.licdn.com/dms/image/D5603AQFsbbI0dt1L7g/profile-displayphoto-shrink_400_400/0/1713511336053?e=1727913600&v=beta&t=xuvpLJeXu0CMgGFHtnfjpaTWu4rs3QNJuJFy91-EeEQ
show_downloads: false
